#ifndef _ERRORS_H_
#define _ERRORS_H_

#define ERR_IO_CLOSE -9
#define ERR_MALFORMED_UTF8 -10
#define ERR_MALFORMED_UNICODE -11
#define ERR_XML_SYNTAX -12
#define ERR_XML_UNKNOWN_VERSION -13
#define ERR_XML_UNKNOWN_ENCODING -14
#define ERR_EXTENSION_NOT_FOUND -15
#define ERR_BAD_PROTOCOL -16
#define ERR_XMPP_VERSION -17
#define ERR_SASL_NO_KNOWN_METHOD -18
#define ERR_XMPP_ERROR -19
#define ERR_SASL_NO_KNOWN_QOP_METHOD -20
#define ERR_SASL_SERVER_SIGNATURE_MISMATCH -21
#define ERR_BASE64_DECODE -22
#define ERR_SASL -23
#define ERR_XML_NAME_LENGTH_EXCEEDED -24
#define ERR_BUFIO_READER_END_OF_INPUT -25
#define ERR_STREAM_END -26
#define ERR_READ_CLOSE -27
#define ERR_READ_ERROR -28
#define ERR_FEATURE_IS_REQUIRED -29

#endif
